version: "3.9"
services:
  proxy:
    container_name: spotify-pj-proxy
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
  app:
    container_name: spotify-pj-app
    build: ./docker/php
    ports:
      - '5173:5173' #vite用のportを定義
    volumes:
      - ./src:/var/www/html
  db:
    container_name: spotify-pj-db
    build: ./docker/mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - spotify-pj-db-volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - TZ=Asia/Tokyo
    platform: linux/x86_64
  phpmyadmin:
    container_name: fullstack-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '8001:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_ROOT_PASSWORD=root
    platform: linux/x86_64
volumes:
  spotify-pj-db-volume: